services:
  db:
    image: pgvector/pgvector:0.8.0-pg17
    container_name: demo-postgres
    environment:
      POSTGRES_USER: UNSAFE_LOCAL_USER
      POSTGRES_PASSWORD: UNSAFE_LOCAL_PASSWORD
      POSTGRES_DB: demo
      # Do not interfere with existing PostgreSQL containers.
      PGDATA: /var/lib/postgresql-demo/data/pgdata
    ports:
      - "0.0.0.0:5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql-demo/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U UNSAFE_LOCAL_USER -d demo"]
      interval: 5s
      timeout: 5s
      retries: 5
volumes:
  pgdata:
