services:
  db:
    image: pgvector/pgvector:0.8.0-pg17
    container_name: demo-postgres
    environment:
      POSTGRES_USER: UNSAFE_LOCAL_USER
      POSTGRES_PASSWORD: UNSAFE_LOCAL_PASSWORD
      POSTGRES_DB: demo
    ports:
      - "0.0.0.0:5432:5432"
    volumes:
      - pgdata:/var/lib/demo/data
volumes:
  pgdata:
