name: SAI Demo Deployment
run-name: Deployment by ${{ github.actor }}

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}

jobs:
  sai-demo-deployment:
    name: SAI Demo Deployment
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Git Checkout
        uses: actions/checkout@v4
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
      - name: Pulumi Dependency Cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.pulumi/plugins
            ./.cicd/node_modules
          key: ${{ runner.os }}-pulumi-${{ hashFiles('./.cicd/bun.lock') }}
          restore-keys: |
            ${{ runner.os }}-pulumi-
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-region: ${{ secrets.AWS_REGION }}
          role-to-assume: ${{ secrets.AWS_ROLE }}
          role-session-name: default
      - name: Install Pulumi Dependencies
        run: cd ./.cicd && bun install
      - name: Deploy Infrastucture and Application
        uses: pulumi/actions@v3
        with:
          work-dir: ./.cicd
          command: up
          stack-name: ${{ secrets.PULUMI_STACK }}
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
